### ISSUE TITLE
Not able to load the add-on in a new fresh installed environment

### ISSUE THREAD

**Issue by Qeria** [arthurperton/statamic-wordpress-users#2] opened 2023-09-23 07:53 UTC
## Bug description
I'm not able to load the plug-in, prompt me an error "Target class [Controller] does not exist"

## How to Reproduce
1. Login to your CP
2. Click in "Wordpress Users" in the link CP
3. See error

## Expected behavior
To load the Add-on to be able to import users. 

## Extra Detail
Attached the error
<img width="1454" alt="Screenshot 2023-09-23 at 09 46 31" src="https://github.com/arthurperton/statamic-wordpress-users/assets/648164/bb2f2350-8c50-4647-ad39-a735e3b5c1f7">

## Environment
Composer Version: 2.6.3
Environment: local  
Debug Mode: ENABLED
URL: [hide]
Maintenance Mode: OFF
Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED
Drivers
Broadcasting: log
Cache: statamic
Database: musal
Logs: stack / single
Mail: smtp
Queue: sync
Session: file
Localization
Installed: cs, da, de, en, nb, na, nn
LaravelLang\Attributes\Plugin: v2.4.1
LaravelLang\HttpStatuses\Plugin: V3.4.5
[LaravelLang\Lang\Plugin: 13.2.2
Protected Locales: en
Publisher Version: V14.7.0
Statamic
Addons: 9
Antlers: runt ime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.23.1 PRO
Statamic Addons arthurperton/wordpress-users: 1.0.5
jezzdk/statamic-wp-import: 1.6.0
statamic/seo-pro: 5.2.2
stillat/meerkat: 3.1.1
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.6
studio1902/statamic-peak-seo: 7.0.3
lain studio1902/statamic-peak-tools: 3.2
teamnov/statamic-images-missing-alt: 1.0.1

**Statamic version:** 4.23.1

**PHP version:** 8.2.9

**Addon version:** 1.0.5

**Install method for Statamic (choose one):**
- Fresh install from `statamic/statamic`

**Comment by arthurperton** [comment] 2023-09-26 13:01
Thanks for your report @Qeria. The issue was caused by some changes in route handling in the newer Laravel versions. It has been resolved in the latest version of the add-on (v1.1.0) which is also fully compatible with Statamic v4.

**Closed as completed by arthurperton** 2023-09-26 13:01 UTC
